###
GET http://localhost:4000/api/v2/feedbacks

###
POST http://localhost:4000/api/v2/feedbacks/vote/2
Content-Type: application/json

{
  "vote": 1
}

###
GET http://localhost:4000/api/v2/feedbacks/summary/2
