GET http://localhost:4000/api/v2/languages

###

GET http://localhost:4000/api/v2/languages?orderBy=name&dir=desc&search=a

GET http://localhost:4000/api/v2/languages/3

###

GET http://localhost:4000/api/v2/languages/112

###

POST http://localhost:4000/api/v2/languages/
Content-Type: application/json

{
  "langid": 22,
  "name": "BASIC",
  "dob": 1964,
  "github23_pr": 1.0,
  "github23_stars": 1.0,
  "designer": "John F. Kemeny, Thomas E. Kurtz",
  "maintainer": "",
  "logo": ""
}

